### ISSUE TITLE
Steaming Support

### ISSUE THREAD

**Issue by nevi-me** [YoshiyukiKato/grpc-kit#1]
Does grpc-kit support streaming? I didn't see it mentioned in the README

**Comment by YoshiyukiKato** [comment]
@nevi-me Thank you for question! And I'm sorry for rough README.
Yes, grpc-kit supports stream. For confirmation, I added some tests for streaming and validated if it passes.

I also added a section about **`use stream`** to README and example codes to `example/stream_greeter`. Please check them out!

**Comment by YoshiyukiKato** [comment]
Close this issue. If you have a new question, please make a new issue or reopen this issue. Thanks!
